// @ts-expect-error TS(2451): Cannot redeclare block-scoped variable 'buildCompl... Remove this comment to see the full error message
const buildComplementaryCertification = require('./build-complementary-certification');
// @ts-expect-error TS(2451): Cannot redeclare block-scoped variable 'Certificat... Remove this comment to see the full error message
const CertificationCandidate = require('../../../../lib/domain/models/CertificationCandidate');

const buildCertificationCandidate = function ({
  id = 123,
  firstName = 'Poison',
  lastName = 'Ivy',
  sex = 'F',
  birthPostalCode = null,
  birthINSEECode = '75101',
  birthCity = 'Perpignan',
  birthProvinceCode = '66',
  birthCountry = 'France',
  email = 'poison.ivy@example.net',
  resultRecipientEmail = 'napoleon@example.net',
  birthdate = '1990-05-06',
  extraTimePercentage = 0.3,
  externalId = 'externalId',
  createdAt = new Date('2020-01-01'),
  authorizedToStart = false,
  sessionId = 456,
  userId = 789,
  organizationLearnerId,
  complementaryCertifications = [buildComplementaryCertification()],
  billingMode = null,
  prepaymentCode = null
}: $TSFixMe = {}) {
  return new CertificationCandidate({
    id,
    firstName,
    lastName,
    sex,
    birthPostalCode,
    birthINSEECode,
    birthCity,
    birthProvinceCode,
    birthCountry,
    email,
    resultRecipientEmail,
    birthdate,
    sessionId,
    externalId,
    extraTimePercentage,
    createdAt,
    authorizedToStart,
    userId,
    organizationLearnerId,
    complementaryCertifications,
    billingMode,
    prepaymentCode,
  });
};

buildCertificationCandidate.pro = function ({
  firstName = 'Poison',
  lastName = 'Ivy',
  sex = 'F',
  birthPostalCode = '75001',
  birthINSEECode = '75101',
  birthCity = 'Perpignan',
  birthProvinceCode = '66',
  birthCountry = 'France',
  email = 'poison.ivy@example.net',
  resultRecipientEmail = 'napoleon@example.net',
  birthdate = '1990-05-06',
  extraTimePercentage = 0.3,
  externalId = 'externalId',
  authorizedToStart = false,
  sessionId = 456,
  complementaryCertifications = [],
  billingMode = 'FREE',
}) {
  return new CertificationCandidate({
    firstName,
    lastName,
    sex,
    birthPostalCode,
    birthINSEECode,
    birthCity,
    birthProvinceCode,
    birthCountry,
    email,
    resultRecipientEmail,
    birthdate,
    sessionId,
    externalId,
    extraTimePercentage,
    authorizedToStart,
    complementaryCertifications,
    billingMode,
  });
};

buildCertificationCandidate.notPersisted = function ({
  firstName = 'Poison',
  lastName = 'Ivy',
  sex = 'F',
  birthPostalCode = '75001',
  birthINSEECode = '75101',
  birthCity = 'Perpignan',
  birthProvinceCode = '66',
  birthCountry = 'France',
  email = 'poison.ivy@example.net',
  resultRecipientEmail = 'napoleon@example.net',
  birthdate = '1990-05-06',
  extraTimePercentage = 0.3,
  externalId = 'externalId',
  authorizedToStart = false,
  sessionId = 456,
  complementaryCertifications = [],
}) {
  return new CertificationCandidate({
    firstName,
    lastName,
    sex,
    birthPostalCode,
    birthINSEECode,
    birthCity,
    birthProvinceCode,
    birthCountry,
    email,
    resultRecipientEmail,
    birthdate,
    sessionId,
    externalId,
    extraTimePercentage,
    authorizedToStart,
    complementaryCertifications,
  });
};

// @ts-expect-error TS(2580): Cannot find name 'module'. Do you need to install ... Remove this comment to see the full error message
module.exports = buildCertificationCandidate;
