exports.up = async function(knex) {
  await knex.raw('CREATE VIEW "answers_shuffled" AS SELECT * FROM "answers" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "assessment-results_shuffled" AS SELECT * FROM "assessment-results" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "assessments_shuffled" AS SELECT * FROM "assessments" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "authentication-methods_shuffled" AS SELECT * FROM "authentication-methods" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "badge-acquisitions_shuffled" AS SELECT * FROM "badge-acquisitions" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "badge-criteria_shuffled" AS SELECT * FROM "badge-criteria" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "badge-partner-competences_shuffled" AS SELECT * FROM "badge-partner-competences" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "badges_shuffled" AS SELECT * FROM "badges" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "campaign-participations_shuffled" AS SELECT * FROM "campaign-participations" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "campaigns_shuffled" AS SELECT * FROM "campaigns" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "certification-candidates_shuffled" AS SELECT * FROM "certification-candidates" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "certification-center-memberships_shuffled" AS SELECT * FROM "certification-center-memberships" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "certification-centers_shuffled" AS SELECT * FROM "certification-centers" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "certification-challenges_shuffled" AS SELECT * FROM "certification-challenges" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "certification-courses_shuffled" AS SELECT * FROM "certification-courses" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "certification-issue-reports_shuffled" AS SELECT * FROM "certification-issue-reports" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "competence-evaluations_shuffled" AS SELECT * FROM "competence-evaluations" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "competence-marks_shuffled" AS SELECT * FROM "competence-marks" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "feedbacks_shuffled" AS SELECT * FROM "feedbacks" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "finalized-sessions_shuffled" AS SELECT * FROM "finalized-sessions" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "knowledge-element-snapshots_shuffled" AS SELECT * FROM "knowledge-element-snapshots" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "knowledge-elements_shuffled" AS SELECT * FROM "knowledge-elements" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "memberships_shuffled" AS SELECT * FROM "memberships" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "organization-invitations_shuffled" AS SELECT * FROM "organization-invitations" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "organization-tags_shuffled" AS SELECT * FROM "organization-tags" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "organizations_shuffled" AS SELECT * FROM "organizations" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "partner-certifications_shuffled" AS SELECT * FROM "partner-certifications" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "pix_roles_shuffled" AS SELECT * FROM "pix_roles" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "pole-emploi-sendings_shuffled" AS SELECT * FROM "pole-emploi-sendings" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "reset-password-demands_shuffled" AS SELECT * FROM "reset-password-demands" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "schooling-registrations_shuffled" AS SELECT * FROM "schooling-registrations" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "sessions_shuffled" AS SELECT * FROM "sessions" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "stages_shuffled" AS SELECT * FROM "stages" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "tags_shuffled" AS SELECT * FROM "tags" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "target-profile-shares_shuffled" AS SELECT * FROM "target-profile-shares" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "target-profiles_shuffled" AS SELECT * FROM "target-profiles" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "target-profiles_skills_shuffled" AS SELECT * FROM "target-profiles_skills" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "tutorial-evaluations_shuffled" AS SELECT * FROM "tutorial-evaluations" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "user-orga-settings_shuffled" AS SELECT * FROM "user-orga-settings" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "user_tutorials_shuffled" AS SELECT * FROM "user_tutorials" ORDER BY RANDOM()');
  await knex.raw('CREATE VIEW "users_pix_roles_shuffled" AS SELECT * FROM "users_pix_roles" ORDER BY RANDOM()');
};

exports.down = async function(knex) {
  await knex.raw('DROP VIEW "assessment-results_shuffled"');
  await knex.raw('DROP VIEW "assessments_shuffled"');
  await knex.raw('DROP VIEW "authentication-methods_shuffled');
  await knex.raw('DROP VIEW "badge-acquisitions_shuffled"');
  await knex.raw('DROP VIEW "badge-criteria_shuffled"');
  await knex.raw('DROP VIEW "badge-partner-competences_shuffled"');
  await knex.raw('DROP VIEW "badges_shuffled"');
  await knex.raw('DROP VIEW "campaign-participations_shuffled"');
  await knex.raw('DROP VIEW "campaigns_shuffled"');
};
